#!/usr/bin/env bash

DEPOT_TOOLS=$(dirname "$0")/..

# Platforms without a hermetic CPython CIPD package can opt out of the
# hermetic interpreter by setting DEPOT_TOOLS_BOOTSTRAP_PYTHON3=0.
if [[ "X$DEPOT_TOOLS_BOOTSTRAP_PYTHON3" == "X0" ]]; then
  exec python3 "$@"
fi

# Same opt out for platforms with no hermetic CPython CIPD package.
case "$HOSTTYPE" in
  s390x | powerpc64 | powerpc64le)
    exec python3 "$@"
    ;;
esac

if [[ ! -f "$DEPOT_TOOLS/python3_bin_reldir.txt" ]]; then
  cat >&2 <<EOF
python3_bin_reldir.txt not found. need to initialize depot_tools by
running gclient, update_depot_tools or ensure_bootstrap.
EOF
  exit 1
fi

if [ "$OSTYPE" = "msys" ]
then
  PYTHON3_BIN_DIR="$DEPOT_TOOLS/$(sed -e 's-\\-/-g' $DEPOT_TOOLS/python3_bin_reldir.txt)"
else
  PYTHON3_BIN_DIR="$DEPOT_TOOLS/$(<"$DEPOT_TOOLS/python3_bin_reldir.txt")"
fi
PATH="$PYTHON3_BIN_DIR":"$PYTHON3_BIN_DIR/Scripts":"$PATH"
"$PYTHON3_BIN_DIR/python3" "$@"
